version: '3'
services:
  ernie:
    image: giovtorres/docker-centos7-slurm:latest
    hostname: ernie
    command: tail -f /dev/null
    expose: 
      - "6817"
      - "6818"
      - "6819"
  wt:
    build: ./wt
    hostname: wt
    entrypoint: tail -f /dev/null
    depends_on:
     - ernie  
    volumes:
    - ./wt/sWebView:/sWebView   
    ports:
    - "8080:8080"
    links:
       - ernie
