---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install dependencies
  yum:
    name: "{{ item }}" 
    state: latest
  with_items:
    - bash-completion
    - bzip2
    - gcc
    - gcc-c++
    - git
    - make
    - mariadb-server
    - mariadb-devel
    - munge
    - munge-devel
    - perl
    - psmisc
    - python-devel
    - python-pip
    - python34
    - python34-devel
    - python34-pip
    - supervisor
    - vim-enhanced
    - wget

- name: Clean yum cache
  command: yum clean all

- name: Remove yum cache directory
  file:
    path: /var/cache/yum
    state: absent

- name: Install python27 modules | pip
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip2.7
    state: present
  with_items:
    - Cython
    - nose

- name: Install python34 modules | pip
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3.4
    state: present
  with_items:
    - Cython
    - nose

- name: Add slurm group
  group:
    name: slurm
    system: yes
    state: present

- name: Add slurm user
  user:
    name: slurm
    group: slurm
    system: yes
    state: present

- name: Get Slurm source
  get_url:
    url: https://download.schedmd.com/slurm/slurm-17.11.2.tar.bz2
    dest: /root/slurm.tar.bz2
    checksum: md5:9c8dcc1737a36ab859612d64ec389847
  register: slurm_download

- name: Create /usr/local/src/slurm
  file:
    path: /usr/local/src/slurm
    state: directory

- name: Unarchive slurm source
  unarchive:
    src: /root/slurm.tar.bz2
    dest: /usr/local/src/slurm
    extra_opts: "--strip-components=1"
    remote_src: yes
  when: slurm_download|changed

- name: Delete tarball source
  file:
    path: /root/slurm.tar.bz2
    state: absent

- name: Configure slurm
  command: |
    ./configure --enable-debug --enable-front-end --prefix=/usr \
      --sysconfdir=/etc/slurm --with-mysql_config=/usr/bin \
      --libdir=/usr/lib64
  args:
    chdir: /usr/local/src/slurm

- name: Build and install slurm
  make:
    chdir: /usr/local/src/slurm
    target: install

- name: Create /etc/slurm
  file:
    path: /etc/slurm
    state: directory

- name: Copy sample files
  copy:
    src: "/usr/local/src/slurm/{{ item.src }}"
    dest: "/etc/slurm/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    remote_src: yes
  with_items:
    - { src: etc/cgroup.conf.example, dest: cgroup.conf.example } 
    - { src: etc/slurm.conf.example, dest: slurm.conf.example } 
    - { src: etc/slurm.epilog.clean, dest: slurm.epilog.clean } 
    - { src: etc/slurmdbd.conf.example, dest: slurmdbd.conf.example }

- name: Copy slurm_completion
  copy:
    src: /usr/local/src/slurm/contribs/slurm_completion_help/slurm_completion.sh
    dest: /etc/profile.d/slurm_completion.sh
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: Create slurm directories
  file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: 0770
  with_items:
    - /var/spool/slurmd
    - /var/run/slurmd
    - /var/lib/slurmd
    - /var/log/slurm

- name: Create slurm sysconfig
  file:
    path: /etc/sysconfig/slurm
    state: directory

- name: Create munge key
  command: /sbin/create-munge-key
  args:
    creates: /etc/munge/munge.key

- name: Delete source unarchived
  file:
    path: /usr/local/src/slurm
    state: absent

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: slurm.conf, dest: /etc/slurm/slurm.conf }
    - { src: slurmdbd.conf, dest: /etc/slurm/slurmdbd.conf }
    - { src: supervisord.conf, dest: /etc/supervisord.conf }

- name: Copy executable scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0770
  with_items:
    - { src: docker-entrypoint.sh, dest: /usr/local/bin/docker-entrypoint.sh }
